### ISSUE TITLE
API: Add an Events object

### ISSUE THREAD

**Issue by lander2k2** [threeport/threeport#8]
The events API is for controllers to publish events that are important for end users.  When controllers encounter conditions that will or may prevent desired state from being reconciled according to declarations by users, controllers should publish useful human readable messages to this API.

Following is an example of an event object the dependency controller would create in response to the creation of a workload definition that has a dependency on a workload definition "sample-app".  When the dependency controller finds no such workload definition exists, it can post this event.
```yaml
Event:
  ObjectType: Dependency
  ObjectID: 213
  EventMessage: WorkloadDefinition sample-app does not exist.
```

Now, when a user uses tptctl to create a workload definition with a dependency on another workload definition, tptctl can check the status of the dependency - and if it is "unhealthy" - it can look up the event to give the end user an immediate warning response that it has referenced a workload definition that doesn't exist.
