### ISSUE TITLE
API: Add Dependency Object

### ISSUE THREAD

**Issue by lander2k2** [threeport/threeport#9]
The dependency object is used to map dependency providers to dependency consumers.  A provider is the dependency workload (or supporting service or managed service).  The consumer is the workload that uses the dependency.  For example, if a web app needs a caching layer such as redis to work, the web app is the consumer, the redis cache is the provider.

For example, let's take a workload called `sampe-app` that has a dependency called `sample-service`.

The workload definitions for each look as follows:
```yaml
WorkloadDefinition:
  Name: sample-app
  YAMLDocument: sample-app-manifest.yaml
  Dependencies:
    - Dependency:
        Name: sample-service-dep
        WorkloadDefinition:
          Name: sample-service
---
WorkloadDefinition:
  Name: sample-service
  YAMLDocument: sample-service-manifest.yaml
```

In response to the `sample-app` workload definition, the workload controller creates a dependency object like this:
```yaml
Dependency:
  Name: sample-service-dep
  Providers:
    - WorkloadDefinition:
        Name: sample-service
  ConsumingDefinitions:
    - WorkloadDefinition:
        Name: sample-app
```
The consuming definition is included to map the dependency to the consuming workload definition so that client workloads can warn users if the `sample-service` definition is missing.

When an instance of sample app is created that looks like this:
```yaml
Workload Instance:
  Name: sample-app-0
  WorkloadDefinition:
    Name: sample-app
```
... the workload controller will update the dependency object so that it looks as follows:
```yaml
Dependency:
  Name: sample-service-dep
  Providers:
    - WorkloadDefinition:
        Name: sample-service
  ConsumingDefinitions:
    - WorkloadDefinition:
        Name: sample-app
  ConsumingInstances:
    - WorkloadInstance:
        Name: sample-app-0
```
This will allows the dependency controller to add a `sample-service-0` workload instance and then remove it when the `sample-app` is deleted and the dependency no longer needed.
